### ISSUE TITLE
Incorrect filename in paper_ogs6py_vtuio.ipynb

### ISSUE THREAD

**Issue by cpgr** [joergbuchwald/joss_ogs6py_VTUinterface#4]
The line where the OGS project file is opened in the demo notebook
```
model = OGS(INPUT_FILE="tunnel_ogs6py.prj", PROJECT_FILE="tunnel_exc.prj", MKL=True)
```
refers to a `INPUT_FILE` that doesn't exist in the repository. I think it should just be `INPUT_FILE="tunnel.prj"`.

Interestingly, that cell executes without error, even though the input file doesn't exist. It is only when executing the following cell in the notebook
```
model.replace_text("tunnel_exc", xpath="./time_loop/output/prefix")
```
that an error is thrown
```
(lots of stack traces here)
OSError: Error reading file 'tunnel_ogs6py.prj': failed to load external entity "tunnel_ogs6py.prj"
```

Ref openjournals/joss-reviews#3673

**Comment by cpgr** [comment]
Note: this example is also listed in the JOSS paper, so make sure that this works out of the box!

**Comment by joergbuchwald** [comment]
Yes, it is `tunnel.prj`. I corrected this and also a method call somewhere below that has changed meanwhile.
Probably, it is a good idea to check whether the filename exists already when the object is instantiated.

**Comment by cpgr** [comment]
I think checking if the file exists during instantiation is probably a good idea.

Don't forget to change paper.md to `tunnel.prj` as well in the example.

**Comment by joergbuchwald** [comment]
> I think checking if the file exists during instantiation is probably a good idea.
I added now file existence checks to both packages.
